### ISSUE TITLE
mark downloaded / limited parallel downloads

### ISSUE THREAD

**Issue by kismet010** [deolivec/plowdownHL#1]
First of all, awesome script.
I want to make 2 points:
1. Script doesn't mark links on txt as downloaded (or I don't know how). The -m argument doesn't work.
2. It could be really good to have the option to launch limited parallel downloads, for example if I have a megaupload account and I want to download the first 5 links from a text file while waiting rapidshare countdown.

Thanks.

**Comment by deolivec** [comment]
Thanks for your feedback.
1. To command to use to have the download status (even for links on txt) is pdi -d
With this command, several sections appears: download remaining, succeed, ongoing.
2. About the limited parallel downloads, I I will see if I have time to implement this evolution. But, perhaps you could do it ?

**Comment by kismet010** [comment]
Hi, thanks for your fast reply!
1. Yep I know. But I mean commenting out the links or something to mark downloaded files, ie: if I stop the script an rerun later it won't download again the same links.
2. Me implementing this function? lol I'm too noob.

**Comment by deolivec** [comment]
You are welcome
- OK, I better understand your request. Currently, the input file is only seen as an input file and not a download status file. The program behavior is :

Program is running: if same links are added with text file or command, the links will not be added.
Program is stopped: you pass the same input file, yes, the files will be downloaded twice. There is no check.

You want to update the input file to avoid the second case. In my point of view, it's not a good behavior as it's only an input file and not a status file. But I have an easy solution for you to get the remaining list. You just have to read this file: /tmp/plowdown/remaining_<SERVER_NAME> . FYI, there is also the /tmp/plowdown/done_<SERVER> file which contains the list of already downloaded files...
- Noob ?!? Scripting is quite easy ;-) And I hopes that my code is easy to read as I'm a script beginner too... But I agree with you that adding this functionality is probably not the easiest way to start scripting ;-)

**Comment by kismet010** [comment]
First I'll go with a "Hello world" script and then tell you lol
Tomorrow I'll check this /tmp thing, sounds interesting.
Thank you very much for your interest
